apiVersion: apps/v1
kind: Deployment
metadata:
  generation: 1
  name: iron-app
  labels:
   app: iron-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iron-app
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template:
    metadata:
      name: iron-app
      labels:
        app: iron-app
    spec:
      containers:
      - name: iron-app
        image: damianesteban/iron-app:latest
        imagePullPolicy: Always
        resources:
          limits:
            cpu: 50m
            memory: 128Mi
          requests:
            cpu: 50m
            memory: 128Mi
        ports:
          - containerPort: 80
        volumeMounts:
          - name:  iron-app-config-volume
            mountPath: /usr/share/nginx/html/config.js
            subPath: config.js
            readOnly: true
      volumes:
        - name: iron-app-config-volume
          configMap:
            name: iron-app-config
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      securityContext: {}
      terminationGracePeriodSeconds: 30
