apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: service
  name: iron-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: iron-app
  template:
    metadata:
      labels:
        app.kubernetes.io/component: service
        app: iron-app
    spec:
      containers:
        - name: iron-app
          image: damianesteban/iron-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          volumeMounts:
            - name:  iron-app-config-volume
              mountPath: /usr/share/nginx/html/config.js
              subPath: config.js
              readOnly: true
      volumes:
        - name: iron-app-config-volume
          configMap:
            name: iron-app-config
