apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: service
  name: multi-stage-react-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: multi-stage-react-app
  template:
    metadata:
      labels:
        app.kubernetes.io/component: service
        app: multi-stage-react-app
    spec:
      containers:
        - name: multi-stage-react-app
          image: damianesteban/helm-app:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          volumeMounts:
            - name:  multi-stage-react-app-config-volume
              mountPath: /usr/share/nginx/html/config.js
              subPath: config.js
              readOnly: true
      volumes:
        - name: multi-stage-react-app-config-volume
          configMap:
            name: multi-stage-react-app-config
