apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: service
  name: iron-app
spec:
  ports:
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 80
  selector:
    app: iron-app
  type: ClusterIP
